### ISSUE TITLE
xiapi-sys v0.1.1 cargo failed to build 

### ISSUE THREAD

**Issue by samrdenis** [Ximea-GmbH/xiapi#14]
I have tried everything I can think of and cannot get this resolved. Looks like a bind-gen error but that is out of my wheel house. 

Dell Precision 5570 ubuntu 20.04.6 LTS 
cargo version 1.75 
rustc 1.75 
ximea is installed on linux in the opt/XIMEA filepath. 
c++ works just fine with cmake. 

error: failed to run custom build command for `xiapi-sys v0.1.1`

Caused by:
  process didn't exit successfully: `/home/mrd/Projects/draw_lines/target/debug/build/xiapi-sys-d42d81e173a5fc14/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=m3api
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=./xiApi.h
  cargo:rerun-if-changed=./wintypedefs.h
  cargo:rerun-if-changed=/usr/include/stdlib.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/libc-header-start.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/include/stdc-predef.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/sys/cdefs.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/wordsize.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/long-double.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/gnu/stubs.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/gnu/stubs-64.h
  cargo:rerun-if-changed=/usr/lib/llvm-10/lib/clang/10.0.0/include/stddef.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/waitflags.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/waitstatus.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/floatn.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/floatn-common.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/long-double.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/sys/types.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/wordsize.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/timesize.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/typesizes.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/time64.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/clock_t.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/clockid_t.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/time_t.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/timer_t.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/lib/llvm-10/lib/clang/10.0.0/include/stddef.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/stdint-intn.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/endian.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/endian.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/endianness.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/byteswap.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/uintn-identity.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/sys/select.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/select.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/wordsize.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/sigset_t.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/time_t.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/endian.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/thread-shared-types.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/wordsize.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/struct_mutex.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/struct_rwlock.h
  cargo:rerun-if-changed=/usr/include/alloca.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/lib/llvm-10/lib/clang/10.0.0/include/stddef.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/stdlib-float.h
  cargo:rerun-if-changed=/usr/lib/llvm-10/lib/clang/10.0.0/include/stdint.h
  cargo:rerun-if-changed=/usr/include/stdint.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/libc-header-start.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/wchar.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/wordsize.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/stdint-intn.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/lib/llvm-10/lib/clang/10.0.0/include/limits.h
  cargo:rerun-if-changed=/usr/include/limits.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/libc-header-start.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/posix1_lim.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/wordsize.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/local_lim.h
  cargo:rerun-if-changed=/usr/include/linux/limits.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/posix2_lim.h
  cargo:rerun-if-changed=/usr/lib/llvm-10/lib/clang/10.0.0/include/stddef.h
  cargo:rerun-if-changed=/usr/lib/llvm-10/lib/clang/10.0.0/include/__stddef_max_align_t.h
  cargo:rerun-if-changed=./m3Identify.h

  --- stderr
  thread 'main' panicked at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/ir/context.rs:878:9:
  "__pthread_cond_s_union_(anonymous_at_/usr/include/x86_64-linux-gnu/bits/thread-shared-types_h_94_17)" is not a valid Ident
  stack backtrace:
     0:     0x55c0aef0e20c - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
     1:     0x55c0aef0e20c - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x55c0aef0e20c - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x55c0aef0e20c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x55c0aef38a30 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
     5:     0x55c0aef38a30 - core::fmt::write::h3a39390d8560d9c9
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
     6:     0x55c0aef0b92f - std::io::Write::write_fmt::h5fc9997dfe05f882
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
     7:     0x55c0aef0dff4 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
     8:     0x55c0aef0dff4 - std::sys_common::backtrace::print::h23a2d212c6fff936
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
     9:     0x55c0aef0f5f7 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
    10:     0x55c0aef0f35f - std::panicking::default_hook::h6038f2eba384e475
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
    11:     0x55c0aef0fa78 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
    12:     0x55c0aef0f95e - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
    13:     0x55c0aef0e6d6 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
    14:     0x55c0aef0f6c2 - rust_begin_unwind
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
    15:     0x55c0ae8ef475 - core::panicking::panic_fmt::hbf0e066aabfa482c
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
    16:     0x55c0aeec05b7 - proc_macro2::fallback::validate_ident::hf7dd3500e9af0250
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.76/src/fallback.rs:828:9
    17:     0x55c0aeec02c2 - proc_macro2::fallback::Ident::new_checked::h611d001de4b66c1e
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.76/src/fallback.rs:760:9
    18:     0x55c0aeec29ff - proc_macro2::imp::Ident::new_checked::h4d2411cc058379d5
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.76/src/wrapper.rs:662:50
    19:     0x55c0aeecebd5 - proc_macro2::Ident::new::he9ebc46871c64977
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.76/src/lib.rs:966:21
    20:     0x55c0ae940919 - bindgen::ir::context::BindgenContext::rust_ident_raw::hcb4ec5bfd09a5c55
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/ir/context.rs:878:9
    21:     0x55c0ae9404ca - bindgen::ir::context::BindgenContext::rust_ident::h12a7800baf95ad69
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/ir/context.rs:870:9
    22:     0x55c0ae9be5f6 - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::h7049cf177f4096a3
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:1731:31
    23:     0x55c0ae997e9b - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::hf8fcdc3f801c24e5
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:806:39
    24:     0x55c0ae9f8364 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::h2edc515fc96df9dd
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:492:17
    25:     0x55c0ae9c58f1 - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::h7049cf177f4096a3
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:2062:13
    26:     0x55c0ae997e9b - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::hf8fcdc3f801c24e5
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:806:39
    27:     0x55c0ae9f8364 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::h2edc515fc96df9dd
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:492:17
    28:     0x55c0ae95ba0a - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}::hae171ad035374d18
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:515:21
    29:     0x55c0aea48c29 - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::h6ae01a0ff19ad9da
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:545:13
    30:     0x55c0ae9f8341 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::h2edc515fc96df9dd
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:483:17
    31:     0x55c0ae965b71 - bindgen::codegen::codegen::{{closure}}::h00aea4c802184227
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:4287:9
    32:     0x55c0ae943142 - bindgen::ir::context::BindgenContext::gen::h56363170d10a7bf3
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/ir/context.rs:1190:19
    33:     0x55c0ae964e3d - bindgen::codegen::codegen::hbd595bd50fdba3ff
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:4251:5
    34:     0x55c0ae96b2fa - bindgen::Bindings::generate::h70a6448f16a10efe
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/lib.rs:2374:32
    35:     0x55c0ae9683b0 - bindgen::Builder::generate::ha60edbd06652332d
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/lib.rs:1478:9
    36:     0x55c0ae8f33b7 - build_script_build::main::hd7ca489a7a82ce47
                                 at /home/mrd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xiapi-sys-0.1.1/build.rs:21:20
    37:     0x55c0ae8f0b7b - core::ops::function::FnOnce::call_once::h6b97505ea3f83695
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
    38:     0x55c0ae8efe1e - std::sys_common::backtrace::__rust_begin_short_backtrace::hdc65aae80bbcb9fe
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:154:18
    39:     0x55c0ae8f07f1 - std::rt::lang_start::{{closure}}::hd1d3d811d9b18875
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:167:18
    40:     0x55c0aef07757 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd95060ecd5e1ca24
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
    41:     0x55c0aef07757 - std::panicking::try::do_call::h6e8cf51db32a6e4b
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
    42:     0x55c0aef07757 - std::panicking::try::h3a52eefe24fe3c29
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
    43:     0x55c0aef07757 - std::panic::catch_unwind::h24c28c23c02c3841
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
    44:     0x55c0aef07757 - std::rt::lang_start_internal::{{closure}}::h705d3c9cbc06ef47
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
    45:     0x55c0aef07757 - std::panicking::try::do_call::ha21f52ba13158470
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
    46:     0x55c0aef07757 - std::panicking::try::h5581346bf6aeb1f8
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
    47:     0x55c0aef07757 - std::panic::catch_unwind::h7919645a6b72e25b
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
    48:     0x55c0aef07757 - std::rt::lang_start_internal::h12de51168669836e
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
    49:     0x55c0ae8f07ca - std::rt::lang_start::he3ee5b7db08d9c7a
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:166:17
    50:     0x55c0ae8f35ae - main
    51:     0x7f36f7c78083 - __libc_start_main
                                 at /build/glibc-wuryBv/glibc-2.31/csu/../csu/libc-start.c:308:16
    52:     0x55c0ae8efd4e - _start
    53:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish..

**Comment by superbort** [comment]
Sorry for the late reply. I could not reproduce this issue on any of my development systems, but I suspect that there is some incompatibility between bindgen and some other library on your system.

I have upgraded some dependencies in both xiapi and xiapi-sys including bindgen. Can you try xiapi v0.1.4 and xiapi-sys v0.1.2 to see if that fixed the issue on your system?
